### ISSUE TITLE
Devtools seem to break reduxs observable support again

### ISSUE THREAD

**Issue by nmaxim** [reduxjs/redux-devtools#1028] opened 2022-01-17 15:54 UTC
Hello. 

After update to v 3.0.3 this error appears:

Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

The "guilty" line is: 

import { from } from 'rxjs';
.....
-> const $store = from(store); 

Looks very similar to https://github.com/reduxjs/redux-devtools/issues/274

**Comment by Methuselah96** [comment] 2022-01-17 16:20
Are you getting any warnings in the console?

**Comment by Methuselah96** [comment] 2022-01-17 17:48
Also, what version of RxJS are you using?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-17 23:26
"rxjs": "^6.5.5", "react-redux": "^7.2.2",

**Comment by markerikson** [comment] 2022-01-17 23:31
@Aidar-Frontend-Developer In this case what matters is the `redux` (or `@reduxjs/toolkit`) version, rather than `react-redux`.

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-17 23:40
@markerikson "@reduxjs/toolkit": "^1.5.0",

**Comment by markerikson** [comment] 2022-01-17 23:45
@Aidar-Frontend-Developer okay. for reference, what actual version of `redux` is showing in your `package-lock.json` or `yarn.lock` file?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-17 23:51
"@reduxjs/toolkit@^1.5.0":
  version "1.5.1"
  resolved "https://registry.yarnpkg.com/@reduxjs/toolkit/-/toolkit-1.5.1.tgz#05daa2f6eebc70dc18cd98a90421fab7fa565dc5"
  dependencies:
    immer "^8.0.1"
    redux "^4.0.0"
    redux-thunk "^2.3.0"
    reselect "^4.0.0"

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-17 23:55
I suppose i need to install symbol-observable package?

**Comment by Methuselah96** [comment] 2022-01-18 00:13
> "@reduxjs/toolkit@^1.5.0": version "1.5.1" resolved "https://registry.yarnpkg.com/@reduxjs/toolkit/-/toolkit-1.5.1.tgz#05daa2f6eebc70dc18cd98a90421fab7fa565dc5" dependencies: immer "^8.0.1" redux "^4.0.0" redux-thunk "^2.3.0" reselect "^4.0.0"

That's the `yarn.lock` entry for `@reduxjs/toolkit`, is there a similar entry for `redux`? It should be near the bottom half of the file since they're in alphabetical order.

> I suppose i need to install symbol-observable package?

You shouldn't need to with the latest versions of Redux and RxJS.

Are you getting any warnings in the Chrome DevTools console?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-18 00:15
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-18 00:17
> > "@reduxjs/toolkit@^1.5.0": version "1.5.1" resolved "https://registry.yarnpkg.com/@reduxjs/toolkit/-/toolkit-1.5.1.tgz#05daa2f6eebc70dc18cd98a90421fab7fa565dc5" dependencies: immer "^8.0.1" redux "^4.0.0" redux-thunk "^2.3.0" reselect "^4.0.0"
> 
> That's the `yarn.lock` entry for `@reduxjs/toolkit`, is there a similar entry for `redux`? It should be near the bottom half of the file since they're in alphabetical order.
> 
> > I suppose i need to install symbol-observable package?
> 
> You shouldn't need to with the latest versions of Redux and RxJS.
> 
> Are you getting any warnings in the Chrome DevTools console?


"redux@^3.6.0 || ^4.0.0", redux@^4.0.0, redux@^4.0.4:
  version "4.1.0"
  resolved "https://registry.yarnpkg.com/redux/-/redux-4.1.0.tgz#eb049679f2f523c379f1aff345c8612f294c88d4"
  dependencies:
    "@babel/runtime" "^7.9.2"

**Comment by Methuselah96** [comment] 2022-01-18 00:21
Does `symbol-observable` show up at all in your `yarn.lock`? If so, what depends on it?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-18 00:22
> Does `symbol-observable` show up at all in your `yarn.lock`? If so, what depends on it?

We don't have it

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-18 07:14
Do you have any ideas about how to fix it?

**Comment by Methuselah96** [comment] 2022-01-18 15:41
I tested it out with those specific version numbers and couldn't reproduce. Can you share the code that you're using the create the Redux store?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-18 15:47
import createSagaMiddleware from 'redux-saga';
import { configureStore, Store } from '@reduxjs/toolkit';
import { promiseMiddleware } from '@adobe/redux-saga-promise';
import { persistStore, Persistor } from 'redux-persist';

import rootReducer from './rootReducer';
import rootSaga from './rootSaga';

// @TODO remove after fixing deprecated libs that are using store directly inside api calls
// eslint-disable-next-line import/no-mutable-exports
export let singletonLikeStore = null;

export const initializeStore = (): { store: Store; persistor: Persistor } => {
  const sagaMiddleware = createSagaMiddleware();

  const store = configureStore({
    reducer: rootReducer,
    middleware: [promiseMiddleware, sagaMiddleware],
  });
  sagaMiddleware.run(rootSaga);

  const persistor = persistStore(store);
  // @ts-ignore
  singletonLikeStore = store;
  return { store, persistor };
};

**Comment by Methuselah96** [comment] 2022-01-18 16:48
I am not able to reproduce the issue. I've tried creating [a project](https://github.com/Methuselah96/test-redux-devtools-issue) similar to yours, but everything seems to work fine. Can you try creating a reproducable example that you can share?

**Comment by Methuselah96** [comment] 2022-01-19 01:47
I understand the problem (I think), but when I try to duplicate your code, I don't have the problem. Can you create a public repository showing the issue?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-19 15:28
I have noticed that 
const store = configureStore({
    reducer: rootReducer,
    middleware: [],
  });

redux-devtools - 3.0.3
behave different with redux-devtools and when it is switched on - it returns Symbol(observable) when it is switched off - it returns @@observable: ƒ observable(), and in one case i need to connect import { from } from 'rxjs/internal/observable/from';
and another case import { from } from 'rxjs';

Maybe if it is not clear i can show it in zoom.

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-19 15:30
import { Observable, from } from 'rxjs';
import { from as strangeFrom } from 'rxjs/internal/observable/from';  

let $store;
  try {
    // @ts-ignore
    $store = from(store);
  } catch (error) {
    // @ts-ignore
    $store = strangeFrom(store);
  }

It helped me, but it looks like a hack.

**Comment by Methuselah96** [comment] 2022-01-20 16:42
I find it very odd that the last code snippet you posted works since `import { from } from 'rxjs';` should be equivalent to `import { from } from 'rxjs/internal/observable/from';` since that's exactly how it's being [exported](https://github.com/ReactiveX/rxjs/blob/78032157f5c1655436829017bbda787565b48c30/src/index.ts#L50) in `index.ts`.

A Zoom call would probably work best at this point. You can email me at the email in my GitHub profile and we can set something up.

**Comment by markerikson** [comment] 2022-01-20 16:44
I would also put in a plug for using https://replay.io as a debugging option here.  @Aidar-Frontend-Developer could record what they're seeing on the local machine, then share the replay with @Methuselah96 to dig through.

**Comment by Methuselah96** [comment] 2022-01-20 16:46
That also sounds great.
@Aidar-Frontend-Developer Do you mind trying out Replay and sending me the recording?

**Comment by Aidar-Frontend-Developer** [comment] 2022-01-27 13:27
@Methuselah96 Where can I send the record of the bug?

**Comment by Methuselah96** [comment] 2022-02-07 23:31
@nmaxim Are you still experiencing this issue?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 23:38
It was fixed by adding polyfill import 'symbol-observable' in root application.

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 23:38
We can close this issue.

**Closed** 2022-02-07 23:38 UTC
Labels: awaiting-author-response, cannot reproduce
