### ISSUE TITLE
Compatibility with react-redux@^7.0.0

### ISSUE THREAD

**Issue by mnesarco** [reduxjs/redux-devtools#473] opened 2019-05-01 21:20 UTC
I am using react-redux 7.0.3, and there is a dependency problem with redux-devtools:

extract of my package.json:

```
  "dependencies": {
    "@ant-design/colors": "^3.0.1",
    "@types/jest": "24.0.12",
    "@types/node": "11.13.8",
    "@types/react": "16.8.15",
    "@types/react-dom": "16.8.4",
    "antd": "^3.16.6",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.0.3",
    "react-router-dom": "^5.0.0",
    "react-scripts": "3.0.0",
    "redux": "^4.0.1",
    "typescript": "3.4.5"
  },

```
```
  "devDependencies": {
    "redux-devtools": "^3.5.0"
  }


```

And the problem is:

`npm ERR! peer dep missing: react-redux@^4.0.0 || ^5.0.0 || ^6.0.0, required by redux-devtools@3.5.0
`

**Comment by pgoldweic** [comment] 2019-05-21 19:25
Similarly, I installed the latest versions of react, redux, react-redux and then redux-devtools, but it gives me a warning possibly equivalent to yours:

redux-devtools@3.5.0 requires a peer of react-redux@^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself

Should I roll back to an earlier version of react-redux in order to use the redux-devtools? Please advise.

**Comment by StephanKuehn** [comment] 2019-06-06 14:12
Any updates on this?

**Comment by benfletcher** [comment] 2019-10-24 15:32
React-redux is now 7.1.1, do we expect any update to support it? As far as I can tell, everything does work with the latest version, but npm warns on the peer dep version mismatch.

Thanks for any feedback on this!

**Comment by lebeier** [comment] 2019-10-27 10:07
Any updates?

**Comment by noobjun** [comment] 2019-11-13 09:28
any updates?

**Comment by quezath** [comment] 2019-11-28 13:09
I will have to ask about this too, any updates?

**Comment by ZachHappel** [comment] 2019-12-01 22:58
Having this issue as well.

**Comment by Methuselah96** [comment] 2019-12-11 23:40
Since this package is no longer actively maintained, I published a fork of it under `redux-devtools-maintained` (https://github.com/Methuselah96/redux-devtools). Feel free to use that to get rid of the warning.

**Comment by Methuselah96** [comment] 2019-12-12 00:21
Since this package is no longer actively maintained, I have [forked it](https://github.com/Methuselah96/redux-devtools) and it is published under [`redux-devtools-maintained`](https://www.npmjs.com/package/redux-devtools-maintained). It can be installed using Yarn with `yarn add redux-devtools@npm:redux-devtools-maintained` or using NPM with `npm i redux-devtools@npm:redux-devtools-maintained`

**Comment by venkat-seshadri** [comment] 2019-12-12 06:25
I am having the same problem

**Comment by quezath** [comment] 2019-12-12 06:37
There was a comment from Nathan Bierema/Methuselah96  about forking redux-devtools. But now I couldn't find it.

Anybody has ideas why? Or where is it?

**Comment by Methuselah96** [comment] 2019-12-12 14:40
Yeah, sorry, I have forked [`redux-devtools`](https://github.com/Methuselah96/redux-devtools) and fixed this issue on it and published it as [`redux-devtools-maintained`](https://www.npmjs.com/package/redux-devtools-maintained) with the intention of maintaining the package.

Originally I posted and said that you can now use that using a package alias (e.g. `yarn add redux-devtools@npm:redux-devtools-maintained`) to make this peer dependency warning go away. The issue is that other packages that have a peer dependency on `redux-devtools` (e.g. `https://github.com/gaearon/redux-devtools-dock-monitor`) will now produce a warning because strictly speaking, `redux-devtools` is not installed. I deleted the comment on this thread because I'm not sure how helpful the forked package is if it produces another peer dependency warning.

Does anyone know any way to fix this issue? The only real solution I can think of is to fork every package that has a peer dependency on `redux-devtools` and re-releasing under a different package name, but that doesn't seem ideal. Thumbs-up this message if you think I should do that anyway.

**Comment by quezath** [comment] 2020-03-20 07:11
Hello @Methuselah96 , saw you comments on #502. 

I just wanted to ask if your exchange with @timdorr has led to any update to this particular issue?
Thanks!

**Comment by Methuselah96** [comment] 2020-03-20 12:05
@quezath No updates yet.
@timdorr Let me know if there's anything I can do to help move this along.

**Comment by timdorr** [comment] 2020-05-04 15:28
Just merged in a PR to add it. We should get it released soon.

**Closed by timdorr** 2020-05-04 15:28 UTC
