### ISSUE TITLE
Can't use advanced API with typescript

### ISSUE THREAD

**Issue by cvlmtg** [reduxjs/redux-devtools#1106] opened 2022-03-06 13:46 UTC
Hi, I'm trying to use `@redux-devtools/extension` v3.2.2 in my project with the advanced api (https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Methods.md) but typescript is giving me an error:

*(typescript) Error: /Users/matteo/dev/monarc/src/with-dev-tools.tsx(115,34): semantic error TS2339: Property 'subscribe' does not exist on type 'ConnectResponse'.*

looking at `node_modules/@redux-devtools/extension/lib/types/index.d.ts` I see:

```
interface ConnectResponse {
    init: (state: unknown) => void;
    send: (action: Action<unknown>, state: unknown) => void;
}
```

so it seems the return type of `window.__REDUX_DEVTOOLS_EXTENSION__.connect()` is indeed incomplete.

Thanks for the help!

**Comment by Methuselah96** [comment] 2022-03-09 15:32
Yes, this is a duplicate of https://github.com/reduxjs/redux-devtools/issues/1097. Feel free to make a PR to update the types. Closing this in favor of the earlier issue.

**Closed by Methuselah96** 2022-03-09 15:32 UTC
