### ISSUE TITLE
Redux window pane blank in dev tools

### ISSUE THREAD

**Issue by tychong82** [reduxjs/redux-devtools#1300] opened 2022-12-22 20:24 UTC
<img width="735" alt="Screen Shot 2022-12-22 at 12 21 26 PM" src="https://user-images.githubusercontent.com/1592393/209219866-41308920-6c9b-4e5d-a611-6cf662187d0e.png">

Chrome: Version 108.0.5359.124 (Official Build) (arm64)
Redux: 3.0.16

**Comment by Methuselah96** [comment] 2022-12-22 20:48
I"m having trouble reproducing. Can you right-click on that screen, press "Inspect", go to the "Console" tab, and see if there are any error messages?

**Comment by Methuselah96** [comment] 2022-12-22 20:49
Potentially a duplicate of https://github.com/reduxjs/redux-devtools/issues/1295.

**Comment by huestack** [comment] 2022-12-23 06:54
@Methuselah96 Hi,

I am getting same blank screen in Brave, and Edge, but only in Incognito/Private window. Here is the screenshot of Dev Console
![image](https://user-images.githubusercontent.com/11208563/209287109-80337e1c-b783-41d4-9a53-d6e3c93e5016.png)

**Comment by Methuselah96** [comment] 2022-12-23 18:03
Thanks, I think what's going on now, working on a fix.

**Closed** 2022-12-26 17:37 UTC

**Comment by huestack** [comment] 2022-12-30 13:19
Code files attached.

    On Monday, 26 December, 2022 at 11:08:08 pm IST, Nathan Bierema ***@***.***> wrote:  
 
 


Closed #1300 as completed via #1302.
