### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by madcapnmckay** [reduxjs/redux-devtools#502] opened 2020-03-02 20:31 UTC
It seems like the redux devtools project has fallen into a state of disrepair. I've been occasionally dipping in and out over the last year, waiting to update to the latest cli package and leverage some of the new features that were added. 

There are a number of issues that I see with the project at present.

- Published NPM versions are out of sync with the current code and documentation. Which is especially confusing for new developers trying to get the tools to work as described.
- Issues are piling up and not being responded to.
- A fair number of PRs that are in need of merging, from as far back as Jan 2019.

I'm sympathetic to the burden of maintaining a OSS project. I was wondering if the current maintainers would be open to allowing others on board. I myself would be open to trying to clean up some of the outstanding items as my team directly benefits from the tooling. 

I'm sure there are others who would be open to sharing some of the burden.

@gaearon @zalmoxisus @timdorr @bvaughn 

Thanks

**Comment by timdorr** [comment] 2020-03-02 20:42
Yeah, definitely. I'm generally pretty permissive about this kind of thing. 

Are there any PRs you want to champion towards merging? Any others you'd like to recruit? 

We can start with write access to the repo and go from there.

**Comment by timdorr** [comment] 2020-03-02 21:44
BTW, I pinged Dan to give me npm access. If Mihail isn't available (he's probably pretty busy) to give access to the Chrome Extension publishing group, we may have to make a new one in the Chrome Web Store.

**Comment by madcapnmckay** [comment] 2020-03-02 21:47
The number 1 issue I'd like to address is the npm version publish disconnect. There are also some PRs/Issues that are related to updating dependencies causing people to have to fork themselves.

I'm hesitant to dive into that before learning some context. I will start to go through the issue backlog and see if I can get the lay of the land.

**Comment by zalmoxisus** [comment] 2020-03-02 22:23
@timdorr I added you to npm. Let me know your email address you want to use for Chrome Extension publishing group as well. It would require some time to check everything before publishing as Chrome autoupdates the extension and in case of some issues it could break many sites (as many leave it in production) and there's also risk of stealing users data in case of some packages being compromised.

There was a lot of work in progress in this repository in order to move all extension's part here, it was intended to change almost everything starting from the ui and ending with monitors and the way of sending data. I got some severe family issues and won't be able to work on it anytime soon. If someone wants to take the leadership here, that would be more than welcome.

**Comment by timdorr** [comment] 2020-03-02 22:34
Perfect, thanks! I'm `<my username>@gmail.com` for all things Google. 

I can take a look through the deployment setup we've got. I've actually been a long-time developer on the CWS, so I've got some tooling I can pull in to help automate that stuff.

I'm more than happy to take that off your plate so you can focus on the important things in life. Hope that all gets better soon!

**Comment by zalmoxisus** [comment] 2020-03-02 23:03
I added you @timdorr. Also I need you to register at https://addons.mozilla.org/en-US/developers/ or if using another address already there let me know for publishing Firefox extension. Thanks for helping!

**Comment by timdorr** [comment] 2020-03-03 01:43
I use `mozilla@timdorr.com` over there.

**Comment by zalmoxisus** [comment] 2020-03-03 12:19
Granted owner rights. The other member who has the right to publish extensions is @jhen0409.

**Comment by timdorr** [comment] 2020-03-03 15:05
Cool, thank you!

**Comment by madcapnmckay** [comment] 2020-03-04 18:42
Great. Thanks @zalmoxisus and @timdorr. I'll try and carve out some time this week to dive in and see if I can be of use.

**Comment by timdorr** [comment] 2020-03-07 17:01
I think I just need to get a handle on the status of this monorepo versus Mihail's original one. There are diverging commits, so I don't want anything important to get lost.

It's on my list to get things taken care of and back on track.

**Comment by Methuselah96** [comment] 2020-03-07 17:43
@timdorr Are you talking about the difference between some of the original repos and Mihail's fork of them to be used for the extension (e.g. https://github.com/alexkuz/redux-devtools-inspector vs. https://github.com/zalmoxisus/remotedev-inspector-monitor)? Do you want me to do the leg-work of trying to reconcile differences between the two and make a PR for anything that was changed in the `remotedev` version?

**Comment by zalmoxisus** [comment] 2020-03-07 22:31
The list of what has moved here is in #412. So basically all the necessary parts except the browser extension and its `redux-devtools-extention` npm package (optional helper used for ts and to replace the global variable). The plan was to rewrite a new version of browser extension from scratch here (with a new way of injecting the script and a new UI), and leave my repo as legacy one.

`redux-devtools` npm package was made by Dan and has nothing to do with browser extension. I can publish that on Monday to fix that issue with packages conflicts.

**Comment by zalmoxisus** [comment] 2020-03-07 22:42
@Methuselah96 those packages with differences at that time were merged in [packages/redux-devtools-inspector](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-inspector).

**Comment by Methuselah96** [comment] 2020-03-07 22:55
@zalmoxisus I see that now, thanks!

@timdorr Which of Mihail's repos are you referring to?

**Comment by Methuselah96** [comment] 2020-03-08 00:49
@zalmoxisus Although, I don't think the latest version of `redux-devtools-inspector` has been published to npm. The latest version on npm is 0.11.3 which was published on 3/5/2017 which doesn't include important fixes like https://github.com/alexkuz/redux-devtools-inspector/commit/5202f01f15779a7a01e6679272a6d5f4566d646f (see https://github.com/reduxjs/redux-devtools/issues/481). I've been unable to use the version of `redux-devtools-inspector` that is on npm and have to rely on on workarounds (like this: https://github.com/alexkuz/redux-devtools-inspector/issues/71#issuecomment-350557267).

**Comment by timdorr** [comment] 2020-03-10 15:42
@Methuselah96 I thought the redux-devtools-extension _was_ this repo. I guess I have those confused. Still learning!

**Comment by Methuselah96** [comment] 2020-03-24 14:05
@timdorr Any updates on this? No worries if not, I just wanted to make sure it hasn't been forgotten since it's been a couple of weeks. I'm looking forward to this project getting back to a maintained state. As always, let me know if there's anything I can do to help move this along.

**Comment by timdorr** [comment] 2020-03-24 17:44
Not at the moment. We just closed our first funding round at [my startup](https://spaceship.run/), so things are kind of hectic, along with all the COVID-19 craziness. I will try to get to it soon.

**Comment by timdorr** [comment] 2020-05-04 15:25
Just added @Methuselah96 to the team and cleaned up a bunch of PRs. Hopefully, that means we're getting things on track. I'm going to close this out, but feel free to open another issue like this if we don't stick to our word :)

**Closed by timdorr** 2020-05-04 15:25 UTC
