### ISSUE TITLE
NPM version mismatch

### ISSUE THREAD

**Issue by earksiinni** [reduxjs/redux-devtools#501] opened 2020-02-26 22:42 UTC
`package.json` for this package claims that the version is `1.0.0`, whereas NPM claims that the latest available version is `0.0.1-1`: https://www.npmjs.com/package/redux-devtools-cli

Could we get an updated version in NPM?

**Comment by Methuselah96** [comment] 2020-04-30 01:24
We're working on getting this project back to a maintained state (see https://github.com/reduxjs/redux-devtools/issues/502). Once that happens we'll be sure to make sure to publish the latest version of all the packages.

**Comment by Methuselah96** [comment] 2020-05-07 06:40
Duplicate of https://github.com/reduxjs/redux-devtools/issues/453.

**Closed by Methuselah96** 2020-05-07 06:40 UTC
Labels: Package: redux-devtools-cli, Type: Maintenance, duplicate
