### ISSUE TITLE
Import state crashed

### ISSUE THREAD

**Issue by vaske** [reduxjs/redux-devtools#645] opened 2020-09-28 23:22 UTC
When I do an export of my app state and right after that I tried to import it fails with error Maximum call stack size exceeded, my state is way big like 14k lines in raw, I tried the same with reset of my state and in that case, it works well. This drives me a bit crazy because it seems it's data related, but then how export works smoothly and why state works without any issue? 

What would be the best way to debug import functionality?

**Comment by Methuselah96** [comment] 2020-09-29 00:17
If you want you could make a Gist with your state is and post it here and I could figure out what the issue. Or send it to nbierema@gmail.com if its confidential.

If neither of those options work for you, you could try looking into the [`redux-devtools-serialize`](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-serialize) package to see if it's an issue with deserialization (which seems the most likely).

**Comment by vaske** [comment] 2020-09-29 09:31
I also get 

```
VM9:1 Uncaught TypeError: i.match is not a function
    at f (<anonymous>:1:6936)
    at e.startingFrom (<anonymous>:1:6136)
    at <anonymous>:1:23330
    at _ (<anonymous>:1:29640)
    at O (<anonymous>:1:29863)
    at S (<anonymous>:1:29753)
```

basically those 2 errors

![image](https://user-images.githubusercontent.com/56588/94540999-5cee8080-0247-11eb-9216-b25a1b3bcfad.png)

**Comment by Methuselah96** [comment] 2020-09-29 17:28
@vaske `i.match` is an error being thrown by your reducer. When you import state, Redux DevTools "re-dispatches" all of your actions. This most likely means you Redux store is not [free from side-effects](https://redux.js.org/style-guide/style-guide#reducers-must-not-have-side-effects).

**Comment by Methuselah96** [comment] 2020-09-29 19:32
You should be able to just open the Chrome DevTools and turn on "pause on exceptions" and see the error is being thrown from. It also looks like you're code is running a production build, so if switch to a development, the error should be easier to read since the variable names won't be obfuscated.

**Comment by vaske** [comment] 2020-09-29 22:07
@Methuselah96 Could you please give more context about this pause on error thingy I'm sure that I miss something because I can't see any error nor been able to stop on error and find where it has been introduced

**Comment by vaske** [comment] 2020-09-30 13:17
this `i.match` occurs from redux-devtools-core/src/utils/filters.js function is filtered because type is '' object passed there is {type: ''}

**Comment by Methuselah96** [comment] 2020-09-30 13:21
Wouldn't it sill work if it was an empty string though? `''.match()` is a function right? When I import your exported into Redux DevTools it doesn't throw any errors, so that's why I was assuming it was something in your code.

**Comment by vaske** [comment] 2020-09-30 13:25
yeah, I do not get an error when I import it to redux without my main code, but in such case I tried to listen to pause on exception and that is what I see. However, debugging my end, seems like something is broken on my redux store

**Comment by Methuselah96** [comment] 2020-10-08 13:24
@vaske Have you been able to figure out the issue? I'm going to close this since I think the issue is with your code, but let me know if you have any more questions.

**Closed by Methuselah96** 2020-10-08 13:24 UTC
