### ISSUE TITLE
Filter still active even after closing out window and emptying 'filter...' input

### ISSUE THREAD

**Issue by jacobbroughton** [reduxjs/redux-devtools#1061] opened 2022-01-28 15:43 UTC
If you have a filter in the 'filter' input and close out the window, the filter is still active after opening a new window but the input is empty.

Once you type something, it removes the previous filter, even though the input was empty prior to typing.

**Comment by Methuselah96** [comment] 2022-01-30 22:42
Thanks for creating the issue! Looks like this is a duplicate of https://github.com/reduxjs/redux-devtools/issues/1059, so we'll keep the discussion centralized there.

**Closed by Methuselah96** 2022-01-30 22:42 UTC
Labels: needs investigation
