### ISSUE TITLE
Redux extension does not show state after upgrading to v.3 or v3.0.3

### ISSUE THREAD

**Issue by sorinpav** [reduxjs/redux-devtools#1007] opened 2022-01-12 17:32 UTC
@Methuselah96 thank you for helping. I'm tagging you directly so you're aware of the issue, since we talked about this. Thanks again!

After both the upgrades done this week, firstly to v3 and then to v3.0.3, we still see `state: undefined` in our app. 

This is how we set up our store: 
```javascript
import thunk from "redux-thunk";

const appReducer = combineReducers({
...
// list of reducers
});

// reference for the RESET_APP bit: https://alligator.io/redux/reset-state-redux/ in case that's what's causing our state to stay as undefined in the extension
const rootReducer = (state, action) => {
  if (action.type === "RESET_APP") {
    state = undefined;
  }

  return appReducer(state, action);
};
const store = window.devToolsExtension
  ? createStore(
      rootReducer,
      composeWithDevTools(applyMiddleware(thunk))
    )
  : createStore(rootReducer, applyMiddleware(thunk));
```

![image](https://user-images.githubusercontent.com/50046459/149190939-d39d98ec-9687-4691-bdb5-ef73060fc747.png)

**Comment by Methuselah96** [comment] 2022-01-12 17:56
Thanks for the issue. Can you add how `composeWithDevTools` is being defined?

**Comment by Methuselah96** [comment] 2022-01-12 18:00
Never mind, the issue is that you're using `window.devToolsExtension`. That was [deprecated](https://github.com/zalmoxisus/redux-devtools-extension/issues/220) in 2.7 and then [removed](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.0) in 3.0. Use `window.__REDUX_DEVTOOLS_EXTENSION__` / `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` instead.

**Comment by Methuselah96** [comment] 2022-01-12 18:00
I'm closing this since I'm highly confident that will fix your issue. Let me know if you have any other issues.

**Closed by Methuselah96** 2022-01-12 18:00 UTC

**Comment by sorinpav** [comment] 2022-01-12 18:07
I'll have a look and let you know if this fixes the issue. Judging by how you said it, it probably will. Thanks so much for the help! I'll update on here @Methuselah96.

**Comment by markerikson** [comment] 2022-01-12 18:12
fwiw, I'd also strongly suggest switching to Redux Toolkit's `configureStore` API, because A) you _should_ be using RTK anyway, and B) it also automatically does the DevTools configuration for you :)

https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#using-configurestore

**Comment by Methuselah96** [comment] 2022-01-12 18:21
Or switch to the [`@redux-devtools/extension` NPM package](https://github.com/reduxjs/redux-devtools/tree/main/packages/redux-devtools-extension) if you're not ready to make the jump to RTK.
