### ISSUE TITLE
DevTools repeating code from removed reducers

### ISSUE THREAD

**Issue by ivoiv** [reduxjs/redux-devtools#559] opened 2020-08-06 13:42 UTC
I have a special component and store setup, where when a certain component mounts, it creates a reducer for itself and adds it to the store via replaceReducer. When the component gets unmounted, it removes its reducer from the store. 

However, every time the component gets mounted again, Redux DevTools re-executes all the code executed by the reducer during **ALL** the component's previous lifetimes. 

If the component was mounted 10 times, and did 10 calls during each lifetime, the 11th time the component is mounted, DevTools repeats all 100 calls.

This does **NOT** trigger an actual action in the DevTools Log, and no dispatches actually get sent, and no changes happen to the state/reducer. 

It **DOES** however repeat all code within the reducer, be it JavaScript code, or API calls.

![image](https://user-images.githubusercontent.com/11502345/89538845-59b4b680-d7fb-11ea-8b0f-7249c7e3f601.png)

1. After clicking a button 10 times clicks, `calls`, a value in the redux store reaches 10(shows 9 due to stale state in the log)
2. After that the component is unmounted, reducer is removed from store.
3. Component gets mounted again, reducer added to store, `calls` initialised to 0.
4. On re-mounting the component(or rather re-inserting the reducer), DevTools "automatically" runs all the code the component executed, without any interaction from me.
5. Furthermore it prints the value of `calls` as it was when the dispatch was originally called, so it has no connection to the actual store, since both at the start and end of those, the value of `calls` in the store is still actually 0.

This does not happen with DevTools disabled from the Chrome Extensions panel, so this is a DevTools problem.

Do you have any tips on how to fix this?

**Comment by Methuselah96** [comment] 2020-08-06 14:04
Thanks for the thorough bug report! Can you create a reproducible example of this happening that I can look it? I have some ideas of what might be happening, but it'll be a lot easier to fix if I have a reproducible example.

**Comment by ivoiv** [comment] 2020-08-06 14:52
@Methuselah96 
Here's a simple reproduction https://codesandbox.io/s/keen-rosalind-xt0mk

Things get really whacky in CodeSandBox.

Depending on when in the application lifetime I open the DevTools window, it produces different "log spam" in different order. Sometimes it spams out of the actions after i remount the component, sometimes it just does them double.

Also, this time it also appears that it actually triggers the store dispatches and updates the value in the store, without any of the dispatches actually appearing in the Inspector however.

I notice also a lot of errors being spat out in the console that I don't see in my own code. Most of them disappear once i deactivate Dev Tools.


The implementation is by the way not the same as my own code as I'm using a lot of hook creators, custom contexts and utility functions, but the jist of it and the result is identical.

**Comment by Methuselah96** [comment] 2020-08-07 03:37
Turns out there was already an issue for this. Try out [this solution](https://github.com/reduxjs/redux-devtools/issues/304#issuecomment-251715413).

Closing for now because I believe this resolved. Let me know if that doesn't fix it.

**Comment by ivoiv** [comment] 2020-08-07 09:21
@Methuselah96 It solves the dispatch repeating problem, but then introduces a new one - It no longer shows the dispatch log/history.

Or rather, it either shows them for a second and then they get deleted from the list, or they get removed when the reducer is removed.

While better than repeating reducers, it certainly diminishes the usefulness of DevTools.

In CodeSandbox
![reducerCodesandbox](https://user-images.githubusercontent.com/11502345/89630343-87ebd200-d89f-11ea-8a60-5e6b45665e11.gif)


In localhost
![reducerLocal](https://user-images.githubusercontent.com/11502345/89630363-8f12e000-d89f-11ea-837c-b9caf4e302e9.gif)

**Comment by Methuselah96** [comment] 2020-08-07 12:47
@ivoiv Part of the problem is that your reducers have side effects. Redux considers it essential that [reducers do not have side effects](https://redux.js.org/style-guide/style-guide#reducers-must-not-have-side-effects).

**Comment by ivoiv** [comment] 2020-08-07 13:28
@Methuselah96 The side effect(console.log) is just for the purpose of debugging the example.
 
Even without it, in the CodeSandBox example, DevTools actually replays the dispatches and changes the value of `someValue` with every re-insert of the reducer. 
While the `shouldHotReload: false` fix does alleviate the problem, it does mess up the log/history functionality of DevTools.

**Comment by Methuselah96** [comment] 2020-08-28 21:11
Turns out that https://github.com/reduxjs/redux-devtools/issues/378 is the original issue where this is brought up. Closing this in favor of that one.

**Closed by Methuselah96** 2020-08-28 21:11 UTC
Labels: needs investigation
